# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "..", "/repository"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    sudo sed -i 's,http://archive,http://de.archive,g' /etc/apt/sources.list
    if [ ! -f /usr/bin/docker ]
    then
        curl -sSL https://get.docker.com | sudo sh
    fi
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get install -y dnsmasq
    sudo echo "interface=docker0" > /etc/dnsmasq.conf
    sudo service dnsmasq restart
    sudo echo 'DOCKER_OPTS="--dns 172.17.0.1"' > /etc/default/docker
    sudo service docker restart
    if [ ! -f /usr/local/bin/docker-compose ]
    then
        curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` | sudo cat > /usr/local/bin/docker-compose
        sudo chmod a+x /usr/local/bin/docker-compose
    fi
    sudo usermod -aG docker vagrant
  SHELL
end
